# Max chances = 10000
PlayerChance: 1
MobChance: 1
Names:
  Player: '&b<name>'
  Skeleton: '&bСкелет'
  Zombie: '&bЗомби'
  Creeper: '&bКрипер'
  Blaze: '&bИфрит'
  Ghast: '&bГаст'
  PigZombie: '&bСвинозомби'
  Enderman: '&bЭндерман'
  LavaSlime: '&bЛавовый слизь'
  Slime: '&bСлизь'
  Spider: '&bПаук'
  Chicken: '&bКурица'
  Pig: '&bСвинюшка'
  Sheep: '&bОвечка'
  Cow: '&bКорова'
  Squid: '&bКальмар'
  Villager: '&bЖитель'
  IronGolem: '&bЖелезный голем'
  MushroomCow: '&bГрибная корова'
  Ocelot: '&bОцелот'
  Wolf: '&bВолк'
  Wither: '&bИссушитель'
  Guardian: '&bСтраж'
  EGuardian: '&bДревний страж'
  Witch: '&bВедьма'