# Max chances = 10000
PlayerChance: 1
MobChance: 1
Names:
  Player: '&b<name>'
  Skeleton: '&bSkeleton'
  Zombie: '&bZombie'
  Creeper: '&bCreeper'
  Blaze: '&bBlaze'
  Ghast: '&bGhast'
  PigZombie: '&bPig Zombie'
  Enderman: '&bEnderman'
  LavaSlime: '&bLava Slime'
  Slime: '&bSlime'
  Spider: '&bSpider'
  Chicken: '&bChicken'
  Pig: '&bPig'
  Sheep: '&bSheep'
  Cow: '&bCow'
  Squid: '&bSquid'
  Villager: '&bVillager'
  IronGolem: '&bIron Golem'
  MushroomCow: '&bMushroom Cow'
  Ocelot: '&bOcelot'
  Wolf: '&bWolf'
  Wither: '&bWither'
  Guardian: '&bGuardian'
  EGuardian: '&bElder Guardian'
  Witch: '&bWitch'